name = "fgof-state"
version = "0.1.0"
license = "MIT"
author = "FortranGoingOnForty"
maintainer = "FortranGoingOnForty"
copyright = "2026"
description = "Persistent app and workspace state helpers for modern Fortran"

[build]
auto-executables = false
auto-tests = true
auto-examples = false

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
fgof-temp = { git = "https://github.com/FortranGoingOnForty/fgof-temp.git", tag = "v0.1.0" }
